name: 🍏 iOS Builds
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: write
 
# Global Settings
env:
  SCONS_FLAGS: >-
    disable_xr=yes 
    engine_update_check=no 
    module_camera_enabled=no 
    module_mobile_vr_enabled=no 
    module_openxr_enabled=no 
    module_webxr_enabled=no 
    vulkan=no  
    debug_symbols=no

jobs:
  ios-template:
    # From https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#choosing-github-hosted-runners
    runs-on: macos-latest
    name: macos Template (target=template_release)
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      # From https://github.com/actions/runner-images/blob/main/images/macos
      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app


      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }}
          platform: ios
          target: template_release


      - name: Upload artifact
        uses: ./.github/actions/upload-artifact

      - name: Zip artifacts
        run: |
          mkdir -p zipbin/
          zip -r9  "zipbin/${{ github.job }}.zip" bin/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ios-gd-Builds
          files: |
            zipbin/*.zip

