name: 🔗 GHA
on:  [push, pull_request, merge_group, workflow_dispatch]
permissions:
  contents: write
 
concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.


  android-build:
    name: 🤖 Android
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    name: 🍏 iOS
    uses: ./.github/workflows/ios_builds.yml

  linux-build:
    name: 🐧 Linux
    uses: ./.github/workflows/linux_builds.yml

  macos-build:
    name: 🍎 macOS
    uses: ./.github/workflows/macos_builds.yml

  windows-build:
    name: 🏁 Windows
    uses: ./.github/workflows/windows_builds.yml

  windowsmsvc-build:
    name: 🏁 Windowsmsvc
    uses: ./.github/workflows/windows_msvcbuilds.yml

  # web-build:
  #   name: 🌐 Web
  #   uses: ./.github/workflows/web_builds.yml
  
  windowsMono-build:
    name: 🏁 windowsMono
    uses: ./.github/workflows/windowsMono_builds.yml
 

  # Second stage: Run all the builds and some of the tests.

  windowsMono_msvn-build:
    name: 🏁 windowsMono_msvn
    uses: ./.github/workflows/windowsMono_msvc_builds.yml

  linuxMono-build:
    name: 🏁 linuxMono
    uses: ./.github/workflows/linuxMono_builds.yml

  linuxx86_64_build:
    name: 🏁  linuxx86_64
    uses: ./.github/workflows/linuxx86_64_builds.yml

  linuxMonox86_64-build:
    name: 🏁 linuxMonox86_64
    uses: ./.github/workflows/linuxx86_64Mono_builds.yml

